setwd()
dir.create("raw_data")
dir.create("scripts")
dir.create("outputs")
dir.create("clean_data")
dir.create("plots")

data <- read.csv(file.choose())
View(data)
str(data)
data$gender_fac <- as.factor(data$gender)
str(data)
data$gender_num <- ifelse(data$gender_fac == "Female", 1, 0)
class(data$gender_num)
str(data)
data$diagnosis_fac <- as.factor(data$diagnosis)
str(data)
data$diagnosis_fac <- factor(data$diagnosis_fac, 
                          levels = c("Normal", "Cancer"))
levels(data$diagnosis_fac)
data$diagnosis_num <- factor(data$diagnosis_fac,
                          levels = c("Normal", "Cancer"),
                          labels = c( 1, 2)) 
data$smoker_fac <- as.factor(data$smoker)
str(data)
data$smoker_fac<- ifelse(data$smoker_fac == "Yes", 1, 0)
class(data$smoker_fac)
str(data)
write.csv(data, file = "clean_data/patient_info_clean.csv")
save.image(file = "full_workspace.RData")
save(data, file = "workspace.RData")
load("workspace.RData")
load("full_workspace.RData")
plot(data$bmi)
plot(data$diagnosis_num)
plot.design(data$gender,data$diagnosis_fac)
